FROM $_FROM

ENV TERM=xterm \
    DEBIAN_FRONTEND=noninteractive \
    USER=root \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US

RUN apt-get update && \
    apt-get -y --no-install-recommends install apt-utils && \
    apt-get -y --no-install-recommends install locales && \
    apt-get -y --no-install-recommends install wget python && \
    localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 && \
    update-locale LANG=en_US.UTF-8 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY default/entrypoint-test.sh /entrypoint.sh

COPY default/integration_test.py /integration_test.py

EXPOSE 80 5432
