FROM $_FROM

ENV TERM=xterm \
    DEBIAN_FRONTEND=noninteractive \
    USER=root \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US

RUN apt-get update && \
    # Setup locales && \
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen && \
    echo "LC_ALL=en_US.UTF-8" >> /etc/default/locale && \
    apt-get -y --no-install-recommends install locales && \
    localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 && \
    update-locale LANG=en_US.UTF-8 && \
    apt-get -y --no-install-recommends install apt-utils && \
    apt-get -y --no-install-recommends install wget python && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY default/entrypoint-test.sh /entrypoint-test.sh
COPY default/entrypoint-test-docker.sh /entrypoint-test-docker.sh

COPY default/run-test.py /run-test.py

#EXPOSE 80 5432
